/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  storySidebar: [{type: 'category', label: 'Part 1: Formation', collapsed: true, items: [
    'Part 1/Prologue_-_The_Beginning',
    'Part 1/On_the_Other_Side_of_the_Tournament',
    'Part 1/Following_the_Flying_Bird',
    'Part 1/Investigation_Team_Formation_Exam',
    'Part 1/Harajuku_Day_Trip',
    'Part 1/To_Izu',
    'Part 1/On_the_Night_of_the_Mountain_Hunt',
    "Part 1/A_Doll's_Melancholy",
    'Part 1/To_the_Site_of_the_Final_Battle',
    'Part 1/In_the_Ruins_of_Where_It_Began',
  ]},
    {
      'Part 2: Complication': [
        'Part 2/2-1_On_a_New_Mission',
        'Part 2/2-2_The_Darkness_Looming_over_the_World',
        'Part 2/2-3_Time_Limit',
        'Part 2/2-4_Surprise_Assault_on_the_Origami_Estate',
        'Part 2/2-5_In_the_Moonlight',
        'Part 2/2-6_The_Fateful_Toji',
        'Part 2/2-7_The_Special_Hazardous_Waste_Leakage_Issue',
        'Part 2/2-8_The_Mysterious_Figure',
        'Part 2/2-9_For_Those_Smiling_Faces',
        'Part 2/2-10_The_Three_Goddesses',
        'Part 2/2-11_The_Netherworld',
      ]
    }, 
    {
      'Part 3: Turmoil': [
        'Part 3/3-1_Assembly',
        'Part 3/3-2_The_Dark_Shadow_Working_Behind_the_Scenes',
        'Part 3/3-3_Takirihime',
        'Part 3/3-4_Defense_of_the_Ministry_of_Defense',
        'Part 3/3-5_Tagitsuhime_and_her_Imperial_Guard',
        'Part 3/3-6_The_Two_from_the_Imperial_Guard',
        'Part 3/3-7_The_Conspiracy_Closing_in_on_Ichikishimahime',
        "Part 3/3-8_Ichikishimahime's_Encirclement",
        'Part 3/3-9_A_Reason_to_Be',
      ]
    },
    {
      'Part 4: Bonds': [
        'Part 4/4-1_The_Raging_Thunder_God',
        'Part 4/4-2_The_Gate_to_the_Netherworld_is_Opened',
        'Part 4/4-3_To_Overthrow_Tagitsuhime',
        'Part 4/4-4_Recovery',
        'Part 4/4-5_The_Boundary_Between_This_World_and_the_Netherworld',
        'Part 4/4-6_The_Final_Battle',
        'Part 4/4-7_A_Chance_Meeting',
        "Part 4/4-8_The_Changing_World",
        'Part 4/Chain_Story_Archives_Part_2.5',
      ]
    },
    {
      'Part 5: Fog at First Light': [
        'Part 5/5-1_Kashuu_Kiyomitsu',
        'Part 5/5-2_The_Instigators_up_North',
        'Part 5/5-3_That_Name_Is',
        'Part 5/5-4_Even_If_It_Scares_Me',
        "Part 5/5-5_Time_Won't_Stop",
        'Part 5/5-6_Tamayori_Toji',
        'Part 5/5-7_Awakening',
        "Part 5/5-8_One_With_the_Flame",
      ]
    },
    {
      'Part 6: Beacon': [
        'Part 6/6-1_The_Morning_Fog_Clears',
        'Part 6/6-2_Live_Fire',
        'Part 6/6-3_Dead_End',
        'Part 6/6-4_Once_More_at_Hand',
        'Part 6/6-5_One_Way_Trip',
      ]
    },
  ],
  episodeSidebar: [
    "episodes/Asakura_Mihono_Episodes",
    "episodes/Setouchi_Chie_Episodes",
    "episodes/Shichinosato_Kofuki_Episodes",
    "episodes/Musumi_Kiyoka_Episodes",
    "episodes/Kitora_Mirja_Episodes",
    "episodes/Yamashiro_Yui_Episodes",
    "episodes/Etou_Kanami_Episodes",
    "episodes/Juujou_Hiyori_Episodes",
    "episodes/Yanase_Mai_Episodes",
    "episodes/Itomi_Sayaka_Episodes",
    "episodes/Mashiko_Kaoru_Episodes",
    "episodes/Kohagura_Ellen_Episodes",
    "episodes/Origami_Yukari_Episodes",
    "episodes/Shidou_Maki_Episodes",
    "episodes/Konohana_Suzuka_Episodes",
    "episodes/Satsuki_Yomi_Episodes",
    "episodes/Tsubakuro_Yume_Episodes",
    "episodes/Hiiragi_Kagari_Episodes",
    "episodes/Fujiwara_Minato_Episodes",
    "episodes/Ban_Tsugumi_Episodes",
    "episodes/Iwakura_Sanae_Episodes",
    "episodes/Inago_Akira_Episodes",
    "episodes/Inami_Suu_Episodes",
    "episodes/Nitta_Hirona_Episodes",
  ],
  // eventSidebar: ["Let's_Vacation_A_Tropical_Resort_Festival", "Yume's_Homecoming", ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
